/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package railway.reservation.system;

import com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException;
import java.awt.Color;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.concurrent.TimeUnit;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Gunesh Madusanka
 */
public class advertisement_railway extends javax.swing.JFrame {

    /**
     * Creates new form advertisement_railway
     */
    int x, y;
    public advertisement_railway() {
        initComponents();
        try {
            station.setSelectedItem(null);
            ResultSet rs;
            Statement st;
            Connection con = db.getDBCon();
            st = con.createStatement();
            String sql = "select * from advertisement";
            rs = st.executeQuery(sql);
            boolean b = false;
            while (rs.next()) {
                DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
                Vector v = new Vector();
                String dat0 = rs.getString("applicant_id");
                String dat1 = rs.getString("NIC");
                String dat2 = rs.getString("name");
                String dat3 = rs.getString("adv_firm");
                String dat4 = rs.getString("adv_brand_name");
                String dat5 = rs.getString("medium");
                String dat6 = rs.getString("station");
                String dat7 = rs.getString("position");
                String dat8 = rs.getString("period_from");
                String dat9 = rs.getString("period_to");
                String dat10 = rs.getString("size");
                String dat11 = rs.getString("charges");
                String dat12 = rs.getString("sketch");

                v.add(dat0);
                v.add(dat1);
                v.add(dat2);
                v.add(dat3);
                v.add(dat4);
                v.add(dat5);
                v.add(dat6);
                v.add(dat7);
                v.add(dat8);
                v.add(dat9);
                v.add(dat10);
                v.add(dat11);
                v.add(dat12);

                dtm.addRow(v);
                b = true;

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        firm = new javax.swing.JTextField();
        brand_name = new javax.swing.JTextField();
        banner = new javax.swing.JCheckBox();
        poster = new javax.swing.JCheckBox();
        rail = new javax.swing.JCheckBox();
        other = new javax.swing.JCheckBox();
        inside = new javax.swing.JCheckBox();
        outside = new javax.swing.JCheckBox();
        outside_rail = new javax.swing.JCheckBox();
        inside_train = new javax.swing.JCheckBox();
        outside_train = new javax.swing.JCheckBox();
        size = new javax.swing.JSpinner();
        from = new com.toedter.calendar.JDateChooser();
        to = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        nic = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        station = new javax.swing.JComboBox();
        path = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        charge = new javax.swing.JTextField();
        charges = new javax.swing.JTextField();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 255));
        setForeground(new java.awt.Color(0, 0, 204));
        setUndecorated(true);

        kGradientPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        kGradientPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                kGradientPanel1MouseDragged(evt);
            }
        });
        kGradientPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kGradientPanel1MousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADVERTISTMENT IN THE RAILWAY NETWORK");

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/shutdown_48px.png"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel16))
        );

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Applicant's Name");

        jLabel3.setText("Advertising Firm");

        jLabel4.setText("Advertising Brand Name");

        jLabel5.setText("Medium of Advertising");

        jLabel6.setText("Located Station");

        jLabel7.setText("Position of the Location");

        jLabel8.setText("Advertising Period From");

        jLabel9.setText("Advertising Period To");

        jLabel10.setText("Size of the Advertising Location");

        jLabel11.setText("Sketch Of the Advertising Location");

        banner.setText("Banner");

        poster.setText("Poster");

        rail.setText("Rail Carriages");

        other.setText("Other");

        inside.setText("Inside the Railway Station Displaying to the inside");
        inside.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insideActionPerformed(evt);
            }
        });

        outside.setText("Inside the Railway Station Displaying to the outside");
        outside.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outsideActionPerformed(evt);
            }
        });

        outside_rail.setText("Outside the Railway Station");
        outside_rail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outside_railActionPerformed(evt);
            }
        });

        inside_train.setText("Inside the train");

        outside_train.setText("Outside the train");
        outside_train.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outside_trainActionPerformed(evt);
            }
        });

        jLabel13.setText("Applicant NIC");

        jLabel14.setText("Applicant ID");

        nic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicActionPerformed(evt);
            }
        });

        station.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Stations between Colombo to Polgahawela", "Stations between Colombo to Aluthgama", "Stations in other sections   " }));
        station.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                stationItemStateChanged(evt);
            }
        });

        jButton5.setText("Choose File");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel13)
                        .addGap(95, 95, 95)
                        .addComponent(nic, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel14)
                        .addGap(102, 102, 102)
                        .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)
                        .addGap(79, 79, 79)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)
                        .addGap(83, 83, 83)
                        .addComponent(firm, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4)
                        .addGap(45, 45, 45)
                        .addComponent(brand_name, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5)
                        .addGap(54, 54, 54)
                        .addComponent(banner)
                        .addGap(21, 21, 21)
                        .addComponent(poster)
                        .addGap(23, 23, 23)
                        .addComponent(rail)
                        .addGap(19, 19, 19)
                        .addComponent(other))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6)
                        .addGap(85, 85, 85)
                        .addComponent(station, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7)
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inside)
                            .addComponent(outside)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(outside_rail))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inside_train)
                            .addComponent(outside_train)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8)
                        .addGap(46, 46, 46)
                        .addComponent(from, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel9)
                        .addGap(58, 58, 58)
                        .addComponent(to, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(path, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(9, 9, 9)
                            .addComponent(size, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(nic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(firm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(brand_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(banner)
                    .addComponent(poster)
                    .addComponent(rail)
                    .addComponent(other))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(station, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(inside)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(outside)))
                .addGap(7, 7, 7)
                .addComponent(outside_rail)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inside_train)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(outside_train)))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(from, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(to, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel11))
                    .addComponent(path, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 255, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIC", "ID", "NAME", "FIRM", "BRAND", "MEDIUM", "LOCATION", "POSITION", "FROM", "TO", "SIZE", "CHARGES", "SKETCH"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel12.setText("Charges");

        jLabel15.setText("Charges Per Day");

        charge.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chargeMouseClicked(evt);
            }
        });

        charges.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chargesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(70, 70, 70)
                                .addComponent(charges))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(29, 29, 29)
                                .addComponent(charge, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel15))
                            .addComponent(charge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(charges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        kGradientPanel2.setBorder(new javax.swing.border.MatteBorder(null));
        kGradientPanel2.setkEndColor(new java.awt.Color(255, 204, 204));
        kGradientPanel2.setkStartColor(new java.awt.Color(255, 255, 102));

        jButton1.setText("INSERT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("LICENCE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("DELETE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setText("FULL REPORT");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap(379, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(28, 28, 28)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addGap(344, 344, 344))
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton6))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kGradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void outside_railActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outside_railActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outside_railActionPerformed

    private void insideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insideActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insideActionPerformed

    private void outsideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outsideActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outsideActionPerformed

    private void outside_trainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outside_trainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outside_trainActionPerformed

    private void nicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nicActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            validate_nic();
            //applicant_id, NIC, name, adv_firm, adv_brand_name, medium, station, posiion, period_from, period_to, size, sketch, charges
            String medium = "";
            if (banner.isSelected()) {
                medium = "Banner" + " | ";
            }
            if (poster.isSelected()) {
                medium += "Poster" + " | ";
            }
            if (rail.isSelected()) {
                medium += "Rail Carriages" + " | ";
            }
            if (other.isSelected()) {
                medium += "Other Medium" + " | ";
            }

            String location = "";
            if (inside.isSelected()) {
                location = "Inside the Railway Station Displaying to the inside" + " | ";
            }
            if (outside.isSelected()) {
                location += "Inside the Railway Station Displaying to the outside" + " | ";
            }
            if (outside_rail.isSelected()) {
                location += "Outside the Railway Station" + " | ";
            }

            if (inside_train.isSelected()) {
                location += "Inside train" + " | ";
            }
            if (outside_train.isSelected()) {
                location += "Outside the train" + " | ";
            }

        
            db.iud("insert into advertisement (applicant_id, NIC, name, adv_firm, adv_brand_name, medium, station, position, period_from, period_to, size, sketch, charges) values"
                   + " ('" + id.getText() + "','" + nic.getText() + "','" + name.getText() + "','" + firm.getText() + "','" + brand_name.getText() + "','" + medium + "','" + station.getSelectedItem().toString() + "','" + location + "','" + from.getDate().toString() + "','" + to.getDate().toString() + "','" + size.getValue() + "','" + path.getText() + "','" + Double.parseDouble(charges.getText()) + "')");

             JOptionPane.showMessageDialog(this, "Insert Succesfully");
            refresh();
        } catch (NullPointerException n) {
            JOptionPane.showMessageDialog(null, "Please Fill All the Data", "Sorry", JOptionPane.ERROR_MESSAGE);
        }
         catch (MySQLIntegrityConstraintViolationException my) {
            JOptionPane.showMessageDialog(null, "Duplicate Entry Detected", "Sorry", JOptionPane.ERROR_MESSAGE);
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void stationItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_stationItemStateChanged
        try {
            if (station.getSelectedIndex() == 0) {
                charge.setText("7");
            }
            if (station.getSelectedIndex() == 1) {
                charge.setText("7");
            }
            if (station.getSelectedIndex() == 2) {
                charge.setText("6");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_stationItemStateChanged

    private void chargeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chargeMouseClicked

    }//GEN-LAST:event_chargeMouseClicked

    private void chargesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chargesMouseClicked
        try {
            int i = (int) size.getValue();
            double day = Double.parseDouble(charge.getText());
            double feet = Double.valueOf(i);
            SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy");
            Date f_date = from.getDate();
            Date s_date = to.getDate();

            long diffIn = Math.abs(s_date.getTime() - f_date.getTime());
            long diff = TimeUnit.DAYS.convert(diffIn, TimeUnit.MILLISECONDS);
            // t2.setText(String.valueOf(diff));
            long new_diff = diff + 1;
            Double price = day * new_diff * feet;
            if (s_date.getTime() < f_date.getTime()) {
                // System.out.println("bigger");
                JOptionPane.showMessageDialog(rootPane, "Wrong input of Date range", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                //System.out.println(Long.toString(diff));
                charges.setText(price.toString());
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_chargesMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            String medium = "";
            if (banner.isSelected()) {
                medium = "Banner" + " | ";
            }
            if (poster.isSelected()) {
                medium += "Poster" + " | ";
            }
            if (rail.isSelected()) {
                medium += "Rail Carriages" + " | ";
            }
            if (other.isSelected()) {
                medium += "Other Medium" + " | ";
            }

            String location = "";
            if (inside.isSelected()) {
                location = "Inside the Railway Station Displaying to the inside" + " | ";
            }
            if (outside.isSelected()) {
                location += "Inside the Railway Station Displaying to the outside" + " | ";
            }
            if (outside_rail.isSelected()) {
                location += "Outside the Railway Station" + " | ";
            }

            if (inside_train.isSelected()) {
                location += "Inside train" + " | ";
            }
            if (outside_train.isSelected()) {
                location += "Outside the train" + " | ";
            }

           
           // String NIC = nic.getText();
           // String ID = id.getText();
          //  int n = Integer.parseInt(NIC);
          //  int i = Integer.parseInt(ID);

          db.iud("update advertisement set name='" + name.getText()+ "',adv_firm='" + firm.getText() + "', adv_brand_name='" + brand_name.getText() + "', medium='" + medium + "', station='" + station.getSelectedItem().toString() + "', position='" + location + "', period_from='" + from.getDate().toString() + "' , period_to='" + to.getDate().toString() + "', size='" +  size.getValue() + "', sketch='" + path.getText() + "' ,charges='" + Double.parseDouble(charges.getText()) + "' where applicant_id='" + id.getText() + "' AND NIC='" + nic.getText() + "'");
         //   db.iud("update advertisement set name='"+name.getText()+"' where applicant_id='" + i + "' AND NIC='" + n + "' ");
         //   System.out.println("sucess");
          // db.iud("DELETE from advertisement where applicant_id='"+id.getText()+"' AND NIC='"+nic.getText()+"' ");
            JOptionPane.showMessageDialog(this, "Update Succesfully");
            refresh();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            JFileChooser jf = new JFileChooser();
            jf.showOpenDialog(null);
            File f = jf.getSelectedFile();
            String filename = f.getAbsolutePath();
            path.setText(filename);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try {
            DefaultTableModel dtm1 = (DefaultTableModel) jTable1.getModel();
            int selectedRow = jTable1.getSelectedRow();
            poster.setSelected(false);
            banner.setSelected(false);
            rail.setSelected(false);
            other.setSelected(false);
             inside.setSelected(false);
             outside.setSelected(false);
             outside_rail.setSelected(false);
             inside_train.setSelected(false);
             outside_train.setSelected(false);
            nic.setText(dtm1.getValueAt(selectedRow, 1).toString());
            id.setText(dtm1.getValueAt(selectedRow, 0).toString());
            name.setText(dtm1.getValueAt(selectedRow, 2).toString());
            firm.setText(dtm1.getValueAt(selectedRow, 3).toString());
            brand_name.setText(dtm1.getValueAt(selectedRow, 4).toString());

            String M = dtm1.getValueAt(selectedRow, 5).toString();
            
            if (M.contains("Poster")) {             
                poster.setSelected(true);
            }
            if (M.contains("Banner")) {
                banner.setSelected(true);
            }
            if (M.contains("Rail Carriages")) {
                rail.setSelected(true);
            }
            if (M.contains("Other")) {
                other.setSelected(true);
            }
            station.setSelectedItem(dtm1.getValueAt(selectedRow, 6));
            
            String L = dtm1.getValueAt(selectedRow, 7).toString();
            if (L.contains("Inside the Railway Station Displaying to the inside")) {             
                inside.setSelected(true);
            }
            if (L.contains("Inside the Railway Station Displaying to the outside")) {
                outside.setSelected(true);
            }
            if (L.contains("Outside the Railway Station")) {
                outside_rail.setSelected(true);
            }
            if (L.contains("Inside the train")) {
                inside_train.setSelected(true);
            }
            if (L.contains("Outside the train")) {
               outside_train.setSelected(true);
            }
           
             int f = Integer.parseInt(dtm1.getValueAt(selectedRow, 10).toString());
             size.setValue(f);
             path.setText(dtm1.getValueAt(selectedRow, 12).toString());
             charges.setText(dtm1.getValueAt(selectedRow, 11).toString());

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            if (id.getText().equals("") || nic.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Plesae provide relevant information first", "Sorry", JOptionPane.ERROR_MESSAGE);
            } else {
                Connection con;
                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/railway", "root", "123");
                

               JasperDesign jdesign = JRXmlLoader.load("C:\\Users\\Gunesh Madusanka\\Documents\\NetBeansProjects\\Railway Reservation System\\src\\railway\\reservation\\system\\advertistment_licence.jrxml");
                String sql = "select * from advertisement where applicant_id='" + id.getText() + "' AND NIC='" + nic.getText() + "'";

                JRDesignQuery updateQuery = new JRDesignQuery();
                updateQuery.setText(sql);
                jdesign.setQuery(updateQuery);
                JasperReport jreport = JasperCompileManager.compileReport(jdesign);
                JasperPrint jPrint = JasperFillManager.fillReport(jreport, null, con);

                JasperViewer.viewReport(jPrint);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            
            String i=id.getText();
            String n=nic.getText();
            System.out.println(i);
            System.out.println(n);
            db.iud("DELETE from advertisement where applicant_id='" +id.getText()+ "' AND NIC='" + nic.getText() + "'");
   //  db.iud("DELETE from train_schedule where transportation_id='" + trans_id.getText() + "' AND train_no='" + t_no.getText() + "'");
             JOptionPane.showMessageDialog(this, "Delete Succesfully");
            refresh();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {

            Connection con;
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/railway", "root", "123");

            JasperDesign jdesign = JRXmlLoader.load("C:\\Users\\Gunesh Madusanka\\Documents\\NetBeansProjects\\Railway Reservation System\\src\\railway\\reservation\\system\\advertisement_full.jrxml");
            String sql = "select * from advertisement";

            JRDesignQuery updateQuery = new JRDesignQuery();
            updateQuery.setText(sql);
            jdesign.setQuery(updateQuery);
            JasperReport jreport = JasperCompileManager.compileReport(jdesign);
            JasperPrint jPrint = JasperFillManager.fillReport(jreport, null, con);

            JasperViewer.viewReport(jPrint);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
       dispose();
    }//GEN-LAST:event_jLabel16MouseClicked

    private void kGradientPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel1MousePressed
       x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_kGradientPanel1MousePressed

    private void kGradientPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel1MouseDragged
       int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx - x, yy - y);
    }//GEN-LAST:event_kGradientPanel1MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(advertisement_railway.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(advertisement_railway.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(advertisement_railway.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(advertisement_railway.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new advertisement_railway().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox banner;
    private javax.swing.JTextField brand_name;
    private javax.swing.JTextField charge;
    private javax.swing.JTextField charges;
    private javax.swing.JTextField firm;
    private com.toedter.calendar.JDateChooser from;
    private javax.swing.JTextField id;
    private javax.swing.JCheckBox inside;
    private javax.swing.JCheckBox inside_train;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JTextField name;
    private javax.swing.JTextField nic;
    private javax.swing.JCheckBox other;
    private javax.swing.JCheckBox outside;
    private javax.swing.JCheckBox outside_rail;
    private javax.swing.JCheckBox outside_train;
    private javax.swing.JTextField path;
    private javax.swing.JCheckBox poster;
    private javax.swing.JCheckBox rail;
    private javax.swing.JSpinner size;
    private javax.swing.JComboBox station;
    private com.toedter.calendar.JDateChooser to;
    // End of variables declaration//GEN-END:variables
void refresh() {
        try {
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);
            ResultSet rs;
            Statement st;
            Connection con = db.getDBCon();
            st = con.createStatement();
            String sql = "select * from advertisement";
            rs = st.executeQuery(sql);
            boolean b = false;
            while (rs.next()) {

                Vector v = new Vector();
                String dat0 = rs.getString("applicant_id");
                String dat1 = rs.getString("NIC");
                String dat2 = rs.getString("name");
                String dat3 = rs.getString("adv_firm");
                String dat4 = rs.getString("adv_brand_name");
                String dat5 = rs.getString("medium");
                String dat6 = rs.getString("station");
                String dat7 = rs.getString("position");
                String dat8 = rs.getString("period_from");
                String dat9 = rs.getString("period_to");
                String dat10 = rs.getString("size");
                String dat11 = rs.getString("charges");
                String dat12 = rs.getString("sketch");

                v.add(dat0);
                v.add(dat1);
                v.add(dat2);
                v.add(dat3);
                v.add(dat4);
                v.add(dat5);
                v.add(dat6);
                v.add(dat7);
                v.add(dat8);
                v.add(dat9);
                v.add(dat10);
                v.add(dat11);
                v.add(dat12);

                dtm.addRow(v);
                b = true;

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

     private void validate_nic() {
        try {
            if (!(nic.getText().matches("^[0-9]{9}[vV]$"))) {
                JOptionPane.showMessageDialog(null, "Invalid Input for NIC ", "Error", JOptionPane.ERROR_MESSAGE);
                nic.setBackground(Color.red);
                nic.setForeground(Color.WHITE);
                nic.setText(null);
            } else {
                nic.setBackground(Color.GREEN);
                nic.setForeground(Color.WHITE);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}
